msg1 = input("Pls, enter the 1st msg: ")
msg2 = input("Pls, enter the 2nd msg: ")
msg3 = input("Pls, enter the 3rd msg: ")
full_message = msg1.strip() + " " + msg2.strip() + " " + msg3.strip()
print(full_message)
